name: Update README with GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build GitHub Pages
        run: npm run build # Modify this command based on how you generate your GitHub Pages content

      - name: Update README
        run: |
          echo '<!--BLOG:START:github-pages-->' > README.md
          curl https://joaomh.github.io/index.html >> README.md
          echo '<!--BLOG:START:github-pages-->' >> README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with GitHub Pages"
          git push
